fix(FEC-12844): Related - autoContinue: true - countdown not canceled
kaltura/playkit-js-related pull request #33
Opened 2023-01-04 14:21 UTC by SivanA-Kaltura

### Description of the Changes

Hide related preview when related list is closed.
Also refactored all components which depend on events for rendering to add/remove their own event listeners.

Resolves FEC-12844

### CheckLists

- [ ] changes have been done against master branch, and PR does not conflict
- [ ] new unit / functional tests have been added (whenever applicable)
- [ ] test are passing in local environment
- [ ] Travis tests are passing (or test results are not worse than on master branch :))
- [ ] Docs have been updated

2023-01-04 15:12 UTC, giladna submitted a review, later dismissed

2023-01-09 16:38 UTC, JonathanTGold requested changes

2023-01-10 15:39 UTC, JonathanTGold approved these changes

2023-01-10 16:17 UTC, SivanA-Kaltura commented on src/components/next/next.tsx
> +      relatedManager.unlisten(RelatedEvent.RELATED_ENTRIES_CHANGED, onEntriesChanged);
added use of decorator

2023-01-10 22:06 UTC, JonathanTGold approved these changes

2023-01-11 12:00 UTC, giladna approved these changes

2023-01-11 12:23 UTC, merged